name: Test-create and publish Docker images

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/test-upload-ghcr.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jj/raku-github-actions
